export const en: any = {
  login: "Sign in",
  username: "Username",
  password: "Password",
  email: "E-mail",
  dataset: "Create a dataset with all the primitives you want",
  tryBeatIt: 'Try "Beat it"',
  filters: "Filters",
  numberOfSongs: "NUMBER OF SONGS",
  genres: "GENRES",
  primitives: "PRIMITIVES",
  years: "YEARS",
  more: "More",
  less: "Less",
  search: "Search",
  apply: "Apply",
  searchResults: "Search results for ",
  exportToCsv: "Export to CSV",
  to: "to",
  tracks: "tracks",
  doASearch: "Start searching to see some results",
  noResults: "No results",
  contentLoading: "Results loading",
  mustBeEmail: "This is not an e-mail format",
  loginButton: "Login",
  welcomeBack: "Welcome back! Please login to your account.",
  forgetPassword: "Forget Password",
  logout: "Sign out",
  admin: "Admin",
  needPermission:
    "You are not logged in or you do not have permission to access this page",
  adminPage: "Admin page",
  createUser: "Create an admin",
  users: "Users",
  create: "Create",
  alphanumeric: "Must be alphanumeric",
  sixCharacters: "Must have at least 6 characters",
  eightCharacters: "Must have at least 8 characters"
};
