export const fr: any = {
  login: "Se connecter",
  username: "Nom d'utilisateur",
  password: "Mot de passe",
  email: "Courriel",
  dataset: "Créez un jeu de données avec toutes les primitives souhaitées",
  tryBeatIt: 'Essayer "Les cowboys fringants"',
  filters: "Filtres",
  numberOfSongs: "NOMBRE DE CHANSONS",
  genres: "GENRES",
  primitives: "PRIMITIVES",
  years: "ANNÉES",
  more: "Plus",
  less: "Moins",
  search: "Recherche",
  apply: "Appliquer",
  searchResults: "Résultats de recherche pour ",
  exportToCsv: "Exporter en CSV",
  to: "à",
  tracks: "chansons",
  doASearch: "Commencer une recherche pour voir des résultats",
  noResults: "Aucune résultats",
  loading: "Chargement",
  contentLoading: "Chargement des résultats",
  mustBeEmail: "Doit suivre le format d'un courriel",
  loginButton: "Connexion",
  welcomeBack: "Re-bienvenue! SVP connectez-vous à votre compte.",
  forgetPassword: "Mot de passe oublié",
  logout: "Déconnexion",
  admin: "Admin",
  needPermission:
    "Vous n'êtes pas connecté ou vous n'avez pas la permission d'accéder cette page",
  adminPage: "Page admin",
  createUser: "Créer un admin",
  addSongs: "Ajouter des chansons",
  users: "Utilisateurs",
  create: "Créer",
  alphanumeric: "Doit être alphanumérique",
  sixCharacters: "Doit contenir au moins 6 caractères",
  eightCharacters: "Doit contenir au moins 8 caractères",
  maximumDbStorage: "Stockage maximum de la base de données",
  currentDatabaseDistribution: "Distribution actuelle de la base de données",
  activatedFilters: "Filtres activés",
  availableOf: "disponible de",
  filterGenres: "Filtrer des genres",
  filterPrimitives: "Filtrer des primitives",
  selectAll: "Tout sélectionner",
  deselectAll: "Effacer",
  pageLoading: "Chargement de la page",
  primitive: "Primitive",
  superPrimitives: "Super primitives",
  value: "Valeur",
  exportCsv: "Exporter les résultats en CSV",
  genre: "Genre",
  currentNumber: "Nombre courant",
  cancel: "Annuler",
  export: "Exporter",
  changeNumberGenres:
    "Vous pouvez modifier le nombre de chansons de chaque genre avant de les exporter.",
  errorModal: "Veuillez corriger les erreurs avant d'exporter",
  album: "Album",
  name: "Nom",
  songsInDatabase: "chansons dans la base de données",
  songs: "Chansons",
  addSongsByGenre: "Rajout de chansons par genre",
  addSongsByNumber: "Rajout de chansons par nombre",
  add: "Ajouter",
  NumberOfNewGenres: "Nombre de nouveaux genres",
  NumberOfSongsPerGenre: "Nombre de chansons par genre",
  numberForGenre: "Nombre de chansons pour ce genre",
  filterByGenre: "Filtrer par genre"
};
